server:
  port: 8080
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yxw?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
